name: Test

on:
  push:
    branches: [master]
    paths-ignore:
      - 'docs/**'
      - 'playwright-tests/**'
      - 'app/**'
      - '.github/workflows/screenshots.yml'
      - '.github/workflows/docker-image.yml'
      - '.github/workflows/restarting.yml'
  pull_request:
    branches: [master]
    paths-ignore:
      - 'docs/**'
      - 'playwright-tests/**'
      - 'app/**'
      - '.github/workflows/screenshots.yml'
      - '.github/workflows/docker-image.yml'
      - '.github/workflows/restarting.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v7

      - name: Setup Plone Buildout
        uses: ./.github/actions/setup-plone-buildout

      - name: Run unit tests
        run: make test
